# Generated by Django 5.1.1 on 2024-09-21 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_event_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('voters', 'Voters'), ('project', 'Project Submission'), ('active', 'Voting Active'), ('complete', 'Completed')], default='voters', max_length=50),
        ),
    ]
