# Generated by Django 5.1.1 on 2024-09-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_user_chain_of_address_user_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='chain_of_address',
            field=models.CharField(default='flow', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='user_address',
            field=models.CharField(default='0x321', max_length=255),
            preserve_default=False,
        ),
    ]
