# Generated by Django 5.1.1 on 2024-09-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_user_chain_of_address_alter_user_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='blockchain_event_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='blockchain_transaction_hash',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
